version: "3"
services:
  app:
    container_name: curriculum-front
    image: index.docker.io/fuze365/curriculum-front:latest
    env_file:
      - .env.front
    networks:
      - local_net
    depends_on:
      - api
      - db
    ports:
      - "8080:8080"
  api:
    container_name: curriculum-back
    image: index.docker.io/fuze365/curriculum-back:latest
    env_file:
      - .env.back
      - .env.db
    networks:
      - local_net
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    container_name: mongo
    image: mongo:4.2.0-bionic
    volumes:
      - /data/db:/data/db
    env_file:
      - .env.db
    networks:
      - local_net
    ports:
      - "27017:27017"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
networks:
  local_net:
    driver: bridge
